-- SQLite Schema for NeoStats Credit Risk Intelligence Platform

-- Applications Table (Core applicant demographic, financial and credit parameters)
CREATE TABLE IF NOT EXISTS applications (
    SK_ID_CURR INTEGER PRIMARY KEY,
    TARGET INTEGER,
    NAME_CONTRACT_TYPE TEXT,
    CODE_GENDER TEXT,
    FLAG_OWN_CAR TEXT,
    FLAG_OWN_REALTY TEXT,
    CNT_CHILDREN INTEGER,
    AMT_INCOME_TOTAL REAL,
    AMT_CREDIT REAL,
    AMT_ANNUITY REAL,
    AMT_GOODS_PRICE REAL,
    NAME_TYPE_SUITE TEXT,
    NAME_INCOME_TYPE TEXT,
    NAME_EDUCATION_TYPE TEXT,
    NAME_FAMILY_STATUS TEXT,
    NAME_HOUSING_TYPE TEXT,
    REGION_POPULATION_RELATIVE REAL,
    DAYS_BIRTH INTEGER,
    DAYS_EMPLOYED REAL,
    DAYS_REGISTRATION REAL,
    DAYS_ID_PUBLISH REAL,
    OWN_CAR_AGE REAL,
    OCCUPATION_TYPE TEXT,
    CNT_FAM_MEMBERS REAL,
    REGION_RATING_CLIENT INTEGER,
    REGION_RATING_CLIENT_W_CITY INTEGER,
    ORGANIZATION_TYPE TEXT,
    EXT_SOURCE_1 REAL,
    EXT_SOURCE_2 REAL,
    EXT_SOURCE_3 REAL
);

-- Bureau Table (Client's previous credits reported to Credit Bureau)
CREATE TABLE IF NOT EXISTS bureau (
    SK_ID_BUREAU INTEGER PRIMARY KEY,
    SK_ID_CURR INTEGER,
    CREDIT_ACTIVE TEXT,
    CREDIT_CURRENCY TEXT,
    DAYS_CREDIT INTEGER,
    CREDIT_DAY_OVERDUE INTEGER,
    DAYS_CREDIT_ENDDATE REAL,
    DAYS_ENDDATE_FACT REAL,
    AMT_CREDIT_MAX_OVERDUE REAL,
    CNT_CREDIT_PROLONG INTEGER,
    AMT_CREDIT_SUM REAL,
    AMT_CREDIT_SUM_DEBT REAL,
    AMT_CREDIT_SUM_LIMIT REAL,
    AMT_CREDIT_SUM_OVERDUE REAL,
    CREDIT_TYPE TEXT,
    DAYS_CREDIT_UPDATE INTEGER,
    AMT_ANNUITY REAL
);

-- Previous Applications Table (All previous applications for Home Credit loans)
CREATE TABLE IF NOT EXISTS previous_applications (
    SK_ID_PREV INTEGER PRIMARY KEY,
    SK_ID_CURR INTEGER,
    NAME_CONTRACT_TYPE TEXT,
    AMT_ANNUITY REAL,
    AMT_APPLICATION REAL,
    AMT_CREDIT REAL,
    AMT_DOWN_PAYMENT REAL,
    AMT_GOODS_PRICE REAL,
    WEEKDAY_APPR_PROCESS_START TEXT,
    HOUR_APPR_PROCESS_START INTEGER,
    FLAG_LAST_APPL_PER_CONTRACT TEXT,
    NFLAG_LAST_APPL_IN_DAY INTEGER,
    RATE_DOWN_PAYMENT REAL,
    RATE_INTEREST_PRIMARY REAL,
    RATE_INTEREST_PRIVILEGED REAL,
    NAME_CASH_LOAN_PURPOSE TEXT,
    NAME_CONTRACT_STATUS TEXT,
    DAYS_DECISION INTEGER,
    NAME_PAYMENT_TYPE TEXT,
    CODE_REJECT_REASON TEXT,
    NAME_TYPE_SUITE TEXT,
    NAME_CLIENT_TYPE TEXT,
    NAME_GOODS_CATEGORY TEXT,
    NAME_PORTFOLIO TEXT,
    NAME_PRODUCT_TYPE TEXT,
    CHANNEL_TYPE TEXT,
    SELLERPLACE_AREA INTEGER,
    NAME_SELLER_INDUSTRY TEXT,
    CNT_PAYMENT REAL,
    NAME_YIELD_GROUP TEXT,
    PRODUCT_COMBINATION TEXT
);

CREATE INDEX IF NOT EXISTS idx_apps_sk_id ON applications(SK_ID_CURR);
CREATE INDEX IF NOT EXISTS idx_bur_sk_id ON bureau(SK_ID_CURR);
CREATE INDEX IF NOT EXISTS idx_prev_app_sk_id ON previous_applications(SK_ID_CURR);
